// <auto-generated />
namespace FinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RemovestationnamefromRide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovestationnamefromRide));
        
        string IMigrationMetadata.Id
        {
            get { return "202102151500436_Remove station name from Ride"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
